name: Meson 151 breaks on Apple

on:
  push:
    branches: [ release, next ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - run: brew install meson
      - run: |
          ninja --version || true
          meson --version || true
          python3 --version || true
          uname -a
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: meson setup out/host .
      - run: meson compile -C out/host
